openapi: 3.0.0

info:
  title: An API to interact with haveibeenpwned.com
  version: "1.0.0"

servers:
  - url: https://haveibeenpwned.com/api/v3

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: hibp-api-key

tags:
  - name: is the account pwned
    description: Is the account part of any breached database.

paths:
  /breachedaccount/{account}:
    get:
      operationId: breachedaccount
      summary: Getting all breaches for an account.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: account
          schema:
            type: string
          required: true
          description: Name of the account.
      responses:
        "200":
          description: OK
        "400":
          description: Incorrect hash format
        "404":
          description: Hash not found
